// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace DBBroker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250803191314_Pocetna")]
    partial class Pocetna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Domain.Licenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Institucija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Licence");
                });

            modelBuilder.Entity("Common.Domain.Majstor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specijalizacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Majstori");
                });

            modelBuilder.Entity("Common.Domain.MajstorLicenca", b =>
                {
                    b.Property<int>("MajstorId")
                        .HasColumnType("int");

                    b.Property<int>("LicencaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.HasKey("MajstorId", "LicencaId");

                    b.HasIndex("LicencaId");

                    b.ToTable("MajstorLicence");
                });

            modelBuilder.Entity("Common.Domain.MajstorLicenca", b =>
                {
                    b.HasOne("Common.Domain.Licenca", "Licenca")
                        .WithMany("MajstorLicenca")
                        .HasForeignKey("LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Domain.Majstor", "Majstor")
                        .WithMany("MajstorLicenca")
                        .HasForeignKey("MajstorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licenca");

                    b.Navigation("Majstor");
                });

            modelBuilder.Entity("Common.Domain.Licenca", b =>
                {
                    b.Navigation("MajstorLicenca");
                });

            modelBuilder.Entity("Common.Domain.Majstor", b =>
                {
                    b.Navigation("MajstorLicenca");
                });
#pragma warning restore 612, 618
        }
    }
}
